ProjectGecko/Models/Post.cs
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectGecko.Models
{
    public class Post
    {
        public ObjectId _id;

        public long PostID { get; set; }

        public string Title { get; set; }

        public long PosterID { get; set; }

        public string[] ImagePaths { get; set; }

        public List<Comment> Comments { get; set; }

        public int Likes { get; set; }

        public List<long> PeopleLiked { get; set; }

        public Post()
        {
            //var mongoClient = new MongoClient("mongodb+srv://admin:password1234@test-un7p6.azure.mongodb.net/test?retryWrites=true&w=majority").GetDatabase("AccountDB");
            //return user by id
            string manualCommand = "{find: 'Posts'}";
            var cmd = new JsonCommand<BsonDocument>(manualCommand);
            var result = DatabaseConnection.RunCommand(cmd);
            var bsonList = result.Elements.ElementAt(0).Value.AsBsonDocument.Elements.ElementAt(0).Value.AsBsonArray.ToList();
            long biggest = 0;
            foreach (var item in bsonList)
            {
                long postId = item.AsBsonDocument.GetElement(1).Value.ToInt64();
                if (postId > biggest)
                {
                    biggest = postId;
                }
            }
            //long idCount = mongoClient.GetCollection<Post>("Posts").Aggregate(def);

            PostID = biggest + 1;
            Comments = new List<Comment>();
            PeopleLiked = new List<long>();
        }

        public static Post GetPost(long Id)
        {
            return DatabaseConnection.GetPost(Id);
        }

        public Account GetPostAccount()
        {
            return DatabaseConnection.GetAccount(PosterID);
        }

        public static List<Post> GetAllPosts()
        {
            return DatabaseConnection.GetAllPosts(true);
        }

        public bool UserLikedPost(long accountid)
        {
            return PeopleLiked.Contains(accountid);
        }
    }
}

ProjectGecko/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using ProjectGecko.Models;

namespace ProjectGecko.Controllers
{
    public class PostController : Controller
    {
        [HttpGet]
        public IActionResult ShowPost(long postid)
        {
            return View(Post.GetPost(postid));
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePost(string Title, IFormFileCollection ImagePaths, int userid)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            if(string.IsNullOrWhiteSpace(Title))
            {
                ModelState.AddModelError("Title", "Please enter a title");
            }
            else
            {
                if (ImagePaths.Any())
                {
                    Account AccountPoster = Account.GetAccount(userid);
                    string[] pathList = new string[ImagePaths.Count];
                    Post newPost = new Post()
                    {
                        Title = Title,
                        PosterID = userid
                    };

                    Directory.CreateDirectory($"wwwroot/Images/Users/{AccountPoster.UserName}/Posts/{newPost.PostID}");
                    int i = 0;
                    foreach (var item in ImagePaths)
                    {
                        
                        var match = Regex.Match(item.FileName, @"^.+(?<extension>\.[A-Za-z]+)$");
                        string ImageExtension = match.Groups["extension"].Value;
                        string imageName = Regex.Replace(item.FileName, @"\s", "+");
                        //constructs path for post storage image
                        string pathForImage = $"~/Images/Users/{AccountPoster.UserName}/Posts/{newPost.PostID}/Image" + i + ImageExtension;
                        //for local copy of image
                        string pathForCopy = $"wwwroot/Images/Users/{AccountPoster.UserName}/Posts/{newPost.PostID}/Image" + i + ImageExtension;
                        pathList[i] = pathForImage;
                        using (FileStream stream = System.IO.File.OpenWrite(pathForCopy))
                        {

                            item.CopyTo(stream);
                        }
                        i++;
                    }

                    newPost.ImagePaths = pathList;

                    //System.Diagnostics.Debug.Write(userid);

                    DatabaseConnection.InsertPost(newPost);

                    return Redirect($"/{newPost.PostID}/ShowPost");
                }
                else
                {
                    Post newPost = new Post()
                    {
                        Title = Title,
                        PosterID = userid
                    };

                    DatabaseConnection.InsertPost(newPost);

                    return Redirect($"/{newPost.PostID}/ShowPost");
                }
            }
            return View();
        }


        [HttpPost]
        public IActionResult AddLike(long PostId)
        {
            Post p = DatabaseConnection.GetPost(PostId);
            if(!p.UserLikedPost(long.Parse(Request.Query["userid"])))
            {
                p.Likes += 1;
                p.PeopleLiked.Add(long.Parse(Request.Query["userid"]));
                DatabaseConnection.UpdatePost(p);
            }

            return Json($"{{\"Likes\": {p.Likes}}}");
        }

        [HttpPost]
        public IActionResult RemoveLike(long PostId)
        {
            Post p = Post.GetPost(PostId);
            if(p.Likes > 0 && p.UserLikedPost(long.Parse(Request.Query["userid"])))
            {
                p.Likes -= 1;
                p.PeopleLiked.Remove(long.Parse(Request.Query["userid"]));
                DatabaseConnection.UpdatePost(p);
            }

            return Json($"{{\"Likes\": {p.Likes}}}");
        }
    }
}

ProjectGecko/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectGecko.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text.RegularExpressions;
using MongoDB.Driver;

namespace ProjectGecko.Controllers
{
    public class UserController : Controller
    {
        public IActionResult ShowFeed()
        {
            return View();
        }
        public IActionResult ShowAccount(long userid)
        {
            Account user = Account.GetAccount(userid);
            ViewBag.Posts = DatabaseConnection.GetUserPosts(user.AccountID);
            ViewBag.CommNum = DatabaseConnection.GetCommissions(userid).Count();
            return View(user);
        }
        [HttpGet]
        public IActionResult CreateAccount()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateAccount(string DisplayName,
            string UserName,
            string PhoneNumber,
            string Email,
            string Password,
            IFormFile profileImage)
        {
            if (string.IsNullOrWhiteSpace(UserName) || Regex.Match(UserName, @"\s").Success)
            {
                ModelState.AddModelError("UserName", "UserName is Invalid. Username cannot be empty or have spaces within it");
                return Redirect("LogInSignUp");
            }
            else if (string.IsNullOrWhiteSpace(Email))
            {
                ModelState.AddModelError("Email", "Email is Required");
                return Redirect("LogInSignUp");
            }
            else if (string.IsNullOrWhiteSpace(Password))
            {
                ModelState.AddModelError("Password", "Password is Invaild");
                return Redirect("LogInSignUp");
            }
            else
            {
                bool userIsTaken = DatabaseConnection.GetAccount(UserName) != null;

                if (userIsTaken)
                {
                    ModelState.AddModelError("UserName", "UserName is taken");
                    return Redirect("LogInSignUp");
                }
                else if (Regex.Match(UserName, @"\s").Success)
                {
                    ModelState.AddModelError("UserName", "UserName may not contain spaces because it ruins file structure");
                    return Redirect("LogInSignUp");
                }
                else
                {
                    DisplayName = string.IsNullOrWhiteSpace(DisplayName) ? UserName : DisplayName;
                    if (ModelState.IsValid)
                    {
                        if (profileImage == null)
                        {
                            string pathForImage = "~/Images/Users/Default/defaultprofile.png";
                            Account account = new Account()
                            {
                                DisplayName = DisplayName,
                                UserName = UserName,
                                PhoneNumber = PhoneNumber,
                                Password = Password,
                                Email = Email,
                                ProfPicPath = pathForImage
                            };
                            DatabaseConnection.InsertAccount(account);
                            return Redirect("/");
                        }
                        else if (profileImage.ContentType.ToString() != "image/png" && profileImage.ContentType.ToString() != "image/jpeg" && profileImage.ContentType.ToString() != "image/jpg")
                        {
                            string pathForImage = "~/Images/Users/Default/defaultprofile.png";
                            Account account = new Account()
                            {
                                DisplayName = DisplayName,
                                UserName = UserName,
                                PhoneNumber = PhoneNumber,
                                Password = Password,
                                Email = Email,
                                ProfPicPath = pathForImage
                            };
                            DatabaseConnection.InsertAccount(account);
                            return Redirect("/");
                        }
                        else
                        {
                            //Grabs extension from image
                            var match = Regex.Match(profileImage.FileName, @"^.+(?<extension>\.[A-Za-z]+)$");
                            string ImageExtension = match.Groups["extension"].Value;
                            //constructs path for account image
                            string pathForImage = $"~/Images/Users/{UserName}/Profile/ProfilePicture" + ImageExtension;
                            //for local copy of image
                            string pathForCopy = $"wwwroot/Images/Users/{UserName}/Profile/ProfilePicture" + ImageExtension;

                            Directory.CreateDirectory($"wwwroot/Images/Users/{UserName}/Profile/");

                            //saves Image
                            using (FileStream stream = System.IO.File.OpenWrite(pathForCopy))
                            {
                                profileImage.CopyTo(stream);
                            }

                            Account account = new Account()
                            {
                                DisplayName = DisplayName,
                                UserName = UserName,
                                PhoneNumber = PhoneNumber,
                                Password = Password,
                                Email = Email,
                                AllowCommissions = "No",
                                ProfPicPath = pathForImage
                            };
                            DatabaseConnection.InsertAccount(account);
                            return Redirect("/");
                        }
                    }
                    return Redirect("LogInSignUp");
                }
            }
        }

        [HttpPost]
        public IActionResult RemoveComm(long CommId)
        {
            long commeeid = long.Parse(Request.Query["commeeid"]);
            Commission toDelete = DatabaseConnection.GetCommission(CommId);
            if(toDelete.CommissioneeID == commeeid)
            {
                DatabaseConnection.RemoveCommission(CommId);
                return Json("{'Status': Ok}");
            }
            else
            {
                return Json("{'Status': Bad}");
            }
        }

        [HttpGet]
        public IActionResult RequestCommission()
        {
            string CommIdStr = Request.Query["CommissioneeId"];
            if (CommIdStr != null)
            {
                ViewBag.CommissioneeId = long.Parse(CommIdStr);
                return View();
            }
            else
            {
                return Redirect("/");
            }
        }

        [HttpPost]
        public IActionResult RequestCommission(long commissioneeID,
            IFormFile imagePath1,
            IFormFile imagePath2,
            IFormFile imagePath3,
            IFormFile imagePath4,
            IFormFile imagePath5,
            string description)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (string.IsNullOrWhiteSpace(description))
            {
                ModelState.AddModelError("Description", "Please enter a description");
                return View();
            }
            else
            {
                if (imagePath1 != null || imagePath2 != null || imagePath3 != null || imagePath4 != null || imagePath5 != null)
                {
                    Commission newCommission = new Commission();
                    Account AccountPoster = Account.GetAccount(Request.Cookies["LoggedUser"]);
                    List<IFormFile> imagePaths = new List<IFormFile>();
                    //string[] pathList = new string[0];
                    if (imagePath1 != null)
                    {
                        imagePaths.Add(imagePath1);
                    }
                    if (imagePath2 != null)
                    {
                        imagePaths.Add(imagePath2);
                    }
                    if (imagePath3 != null)
                    {
                        imagePaths.Add(imagePath3);
                    }
                    if (imagePath4 != null)
                    {
                        imagePaths.Add(imagePath4);
                    }
                    if (imagePath5 != null)
                    {
                        imagePaths.Add(imagePath5);
                    }
                    string[] pathList = new string[imagePaths.Count()];
                    int i = 0;
                    foreach (var item in imagePaths)
                    {

                        var match = Regex.Match(item.FileName, @"^.+(?<extension>\.[A-Za-z]+)$");
                        string ImageExtension = match.Groups["extension"].Value;
                        string imageName = Regex.Replace(item.FileName, @"\s", "+");
                        string pathForImage = $"~/Images/Users/{AccountPoster.UserName}/Commissions/{AccountPoster.AccountID}/{commissioneeID}/{newCommission.CommissionID}/Image" + i + ImageExtension;
                        //for local copy of image
                        string pathForCopy = $"wwwroot/Images/Users/{AccountPoster.UserName}/Commissions/{AccountPoster.AccountID}/{commissioneeID}/{newCommission.CommissionID}/Image" + i + ImageExtension;
                        Directory.CreateDirectory($"wwwroot/Images/Users/{AccountPoster.UserName}/Commissions/{AccountPoster.AccountID}/{commissioneeID}/{newCommission.CommissionID}/");
                        pathList[i] = pathForImage;

ProjectGecko/Views/Post/CreatePost.cshtml
@model ProjectGecko.Models.Post

@{
    ViewData["Title"] = "CreatePost";
    Layout = "~/Views/Layouts/_Layout.cshtml";
}

<h1>CreatePost</h1>

@using (Html.BeginForm("CreatePost", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>The name to be publicly displayed</p>
    <p>Caption: <span>@Html.EditorFor(m => m.Title)</span></p>
    <p>@Html.ValidationMessageFor(m => m.Title)</p>

    <p>Images to Post: <span><input type="file" required name="ImagePaths" multiple /></span></p>
    <p>@Html.ValidationMessageFor(m => m.ImagePaths)</p>

    <input type="submit" />
}

ProjectGecko/Views/Post/ShowPost.cshtml
@using ProjectGecko.Models
@using ProjectGecko
@model ProjectGecko.Models.Post

@{
    ViewData["Title"] = "ShowSinglePost";
    Layout = "~/Views/Layouts/_Layout.cshtml";
    Account LoggedIn = Account.GetAccount(Context.Request.Cookies["LoggedUser"]);
}

<div class="showPostCenter">
    <script src="~/Js/JQuery/jquery-3.4.1.min.js"></script>
    <script src="~/Js/LikeButton.js"></script>

    <div class="PostAndControls">
        @foreach (var item in Model.ImagePaths)
        {
            <div class="slide">
                <img src=@Url.Content(item) alt="Alternate Text" class="postimages singlepostimages" />
            </div>
        }

        <div class="CenterControls">
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
    </div>

    <img src=@Url.Content(Model.GetPostAccount().ProfPicPath) alt="Alternate Text" class="ProfilePicSmall" />
    @{string accountPath1 = "/" + Model.GetPostAccount().AccountID + "/account";}
    <a class="UserDetails" href=@accountPath1>
        <h2>@Model.Title</h2>
        <p class="ProfileName">@Model.GetPostAccount().DisplayName</p>
    </a>

    <div class="LikeSection">
        <p class="LikeCounter">Likes: @Model.Likes</p>
        @if (LoggedIn != null)
        {
            if (Model.UserLikedPost(LoggedIn.AccountID))
            {
                <input type="image" src="~/Images/SiteGraphics/Like.png" class="LikeButton RemoveLike" onclick="RemoveLike(@Model.PostID, @LoggedIn.AccountID)" />
                <input type="image" src="~/Images/SiteGraphics/NoLike.png" style="display:none" class="LikeButton AddLike" onclick="AddLike(@Model.PostID, @LoggedIn.AccountID)" />
            }
            else
            {
                <input type="image" src="~/Images/SiteGraphics/Like.png" style="display: none" class="LikeButton RemoveLike" onclick="RemoveLike(@Model.PostID, @LoggedIn.AccountID)" />
                <input type="image" src="~/Images/SiteGraphics/NoLike.png" class="LikeButton AddLike" onclick="AddLike(@Model.PostID, @LoggedIn.AccountID)" />
            }
        }
    </div>

</div>
<div class="CommentSection">
    @if (LoggedIn != null)
    {
        <div class="UserCommentEnter">
            @using (Html.BeginForm("Comment", "User", FormMethod.Post))
            {
                <textarea type="text" name="CommentText"></textarea>
                <input type="hidden" name="postId" value=@Model.PostID />
                <input type="hidden" name="user" value=@LoggedIn.AccountID />
                <input type="submit" value="Comment" />
            }
        </div>
    }
    else
    {
        <a class="LogInWarning" href="/LogInSignUp">Log In to comment</a>
    }
    <div class="PostCommentList">
        @foreach (Comment item in Model.Comments)
        {
            <div class="Comment">
                @{ string accountPath = "/" + Account.GetAccount(item.CommentPoster).AccountID + "/account"; }
                <a href=@accountPath>
                    <img class="ProfilePicSmall" src=@Url.Content(Account.GetAccount(item.CommentPoster).ProfPicPath) alt="Alternate Text" />
                </a>
                <a class="ProfileName" href=@accountPath>
                    <p class="ProfileName">@Account.GetAccount(item.CommentPoster).DisplayName</p>
                </a>
                <p class="CommentText">@item.Text</p>
            </div>
        }
    </div>
</div>
<script src="~/Js/SlideShowController.js"></script>